CREATE TABLE ACTOR ( 
ACT_ID INTEGER (3),  
ACT_NAME VARCHAR (20),  
ACT_GENDER CHAR (1), 
PRIMARY KEY (ACT_ID)); 

CREATE TABLE DIRECTOR ( 
DIR_ID INTEGER (3),  
DIR_NAME VARCHAR (20),  
DIR_PHONE BIGINT (10), 
PRIMARY KEY (DIR_ID)); 

CREATE TABLE MOVIES ( 
MOV_ID INTEGER (4),  
MOV_TITLE VARCHAR (25), 
MOV_YEAR INTEGER (4),  
MOV_LANG VARCHAR (12),  
DIR_ID INTEGER (3), 
PRIMARY KEY (MOV_ID), 
FOREIGN KEY (DIR_ID) REFERENCES DIRECTOR (DIR_ID));

CREATE TABLE MOVIE_CAST ( 
ACT_ID INTEGER (3),  
MOV_ID INTEGER (4),  
ROLE VARCHAR (10), 
PRIMARY KEY (ACT_ID, MOV_ID), 
FOREIGN KEY (ACT_ID) REFERENCES ACTOR (ACT_ID), 
FOREIGN KEY (MOV_ID) REFERENCES MOVIES (MOV_ID)); 

CREATE TABLE RATING ( 
MOV_ID INTEGER (4),  
REV_STARS VARCHAR (25), 
PRIMARY KEY (MOV_ID), 
FOREIGN KEY (MOV_ID) REFERENCES MOVIES (MOV_ID)); 

 DESC ACTOR; 
 DESC DIRECTOR; 
 DESC MOVIES; 
 DESC MOVIES_CAST;
 DESC RATING; 
  
